# Generated by Django 2.1.7 on 2019-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
